// <auto-generated />
using System;
using Khadra.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Khadra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KhadraDbContext))]
    [Migration("20260903082022_AuditTrailImmutability")]
    partial class AuditTrailImmutability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Khadra.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("previous_value");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("SubjectLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_label");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_entries_actor_user_id");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acted_by_user_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<Guid?>("DepositPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_payment_id");

                    b.Property<Guid?>("ExtendedFromBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("extended_from_booking_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("FreeCancellationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("free_cancellation_deadline");

                    b.Property<DateTimeOffset>("PaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_deadline");

                    b.Property<string>("PaymentOption")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_option");

                    b.Property<DateTimeOffset?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("PickupMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pickup_method");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_bookings_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_bookings_dealer_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_reference");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.BookingStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorParty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_party");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("From")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_changes");

                    b.HasIndex("BookingId", "OccurredAt")
                        .HasDatabaseName("ix_booking_status_changes_booking_id_occurred_at");

                    b.ToTable("booking_status_changes", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.HandoverRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal?>("FuelLevel")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("fuel_level");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("OdometerKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_km");

                    b.PrimitiveCollection<string[]>("PhotoStorageKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("photo_storage_keys");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recorded_by");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_booking_handovers");

                    b.HasIndex("BookingId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_handovers_booking_id_type");

                    b.ToTable("booking_handovers", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.Dealer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("business_name");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CommercialRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commercial_registration");

                    b.Property<string>("CoverStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_storage_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<string>("LogoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_storage_key");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operating_hours");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("ReviewDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_due_at");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_admin_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_dealers");

                    b.HasIndex("CommercialRegistration")
                        .IsUnique()
                        .HasDatabaseName("ix_dealers_commercial_registration");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_dealers_owner_user_id");

                    b.HasIndex("ReviewDueAt")
                        .HasDatabaseName("ix_dealers_review_due_at");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_dealers_verification_status");

                    b.ToTable("dealers", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.DealerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_dealer_documents");

                    b.HasIndex("DealerId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_dealer_documents_dealer_id_type");

                    b.ToTable("dealer_documents", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view_reports");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dealer_employees");

                    b.HasIndex("DealerId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_dealer_employees_dealer_id_user_id");

                    b.ToTable("dealer_employees", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Disputes.DisputeStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("EvidenceStorageKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("evidence_storage_keys");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("party");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_dispute_statements");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_dispute_statements_ticket_id_created_at");

                    b.ToTable("dispute_statements", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Disputes.DisputeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_admin_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("OpenedByParty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("opened_by_party");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dispute_tickets");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_dispute_tickets_booking_id");

                    b.HasIndex("SlaDeadline")
                        .HasDatabaseName("ix_dispute_tickets_sla_deadline");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_dispute_tickets_status");

                    b.ToTable("dispute_tickets", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.IdentityAccess.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FamilyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("family_expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.IdentityAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.IdentityAccess.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verification_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_verification_tokens_user_id_purpose");

                    b.ToTable("verification_tokens", (string)null);
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.Booking", b =>
                {
                    b.OwnsOne("Khadra.Domain.Common.GeoPoint", "DeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_longitude");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");
                        });

                    b.OwnsOne("Khadra.Domain.Bookings.BookingPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("BookingId");

                            b1.Property<string>("FuelPolicy")
                                .IsRequired();

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1
                                .ToJson("pricing")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");

                            b1.OwnsOne("Khadra.Domain.Common.Money", "BalanceDue", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "DailyRate", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "DeliveryFee", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "DepositAmount", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "DepositPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "RentalTotal", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "SecurityDeposit", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "TotalPrice", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Fleet.MileagePolicy", "Mileage", b2 =>
                                {
                                    b2.Property<Guid>("BookingPricingBookingId");

                                    b2.HasKey("BookingPricingBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPricingBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_pricing_booking_id");

                                    b2.OwnsOne("Khadra.Domain.Common.Money", "ExcessFeePerKm", b3 =>
                                        {
                                            b3.Property<Guid>("MileagePolicyBookingPricingBookingId");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 3);

                                            b3.Property<string>("CurrencyCode")
                                                .IsRequired()
                                                .HasMaxLength(3);

                                            b3.HasKey("MileagePolicyBookingPricingBookingId")
                                                .HasName("pk_bookings");

                                            b3.ToTable("bookings");

                                            b3.WithOwner()
                                                .HasForeignKey("MileagePolicyBookingPricingBookingId")
                                                .HasConstraintName("fk_bookings_bookings_mileage_policy_booking_pricing_booking_id");
                                        });

                                    b2.Navigation("ExcessFeePerKm");
                                });

                            b1.Navigation("BalanceDue")
                                .IsRequired();

                            b1.Navigation("DailyRate")
                                .IsRequired();

                            b1.Navigation("DeliveryFee")
                                .IsRequired();

                            b1.Navigation("DepositAmount")
                                .IsRequired();

                            b1.Navigation("DepositPercent")
                                .IsRequired();

                            b1.Navigation("Mileage")
                                .IsRequired();

                            b1.Navigation("RentalTotal")
                                .IsRequired();

                            b1.Navigation("SecurityDeposit")
                                .IsRequired();

                            b1.Navigation("TotalPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("Khadra.Domain.Bookings.BookingTerms", "Terms", b1 =>
                        {
                            b1.Property<Guid>("BookingId");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1
                                .ToJson("terms")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "CommissionPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingTermsBookingId");

                                    b2.HasKey("BookingTermsBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingTermsBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_terms_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "CustomerCancellationPenaltyPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingTermsBookingId");

                                    b2.HasKey("BookingTermsBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingTermsBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_terms_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "DealerPenaltyMaxPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingTermsBookingId");

                                    b2.HasKey("BookingTermsBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingTermsBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_terms_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "DealerPenaltyMinPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingTermsBookingId");

                                    b2.HasKey("BookingTermsBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingTermsBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_terms_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "DepositPercent", b2 =>
                                {
                                    b2.Property<Guid>("BookingTermsBookingId");

                                    b2.HasKey("BookingTermsBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingTermsBookingId")
                                        .HasConstraintName("fk_bookings_bookings_booking_terms_booking_id");
                                });

                            b1.Navigation("CommissionPercent")
                                .IsRequired();

                            b1.Navigation("CustomerCancellationPenaltyPercent")
                                .IsRequired();

                            b1.Navigation("DealerPenaltyMaxPercent")
                                .IsRequired();

                            b1.Navigation("DealerPenaltyMinPercent")
                                .IsRequired();

                            b1.Navigation("DepositPercent")
                                .IsRequired();
                        });

                    b.OwnsOne("Khadra.Domain.Bookings.PenaltyAssessment", "Penalty", b1 =>
                        {
                            b1.Property<Guid>("BookingId");

                            b1.Property<string>("AttributedTo")
                                .IsRequired();

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1
                                .ToJson("penalty")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");

                            b1.OwnsOne("Khadra.Domain.Common.Money", "MaxAmount", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyAssessmentBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("PenaltyAssessmentBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyAssessmentBookingId")
                                        .HasConstraintName("fk_bookings_bookings_penalty_assessment_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "MaxPercent", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyAssessmentBookingId");

                                    b2.HasKey("PenaltyAssessmentBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyAssessmentBookingId")
                                        .HasConstraintName("fk_bookings_bookings_penalty_assessment_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "MinAmount", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyAssessmentBookingId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("PenaltyAssessmentBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyAssessmentBookingId")
                                        .HasConstraintName("fk_bookings_bookings_penalty_assessment_booking_id");
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Percentage", "MinPercent", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyAssessmentBookingId");

                                    b2.HasKey("PenaltyAssessmentBookingId")
                                        .HasName("pk_bookings");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyAssessmentBookingId")
                                        .HasConstraintName("fk_bookings_bookings_penalty_assessment_booking_id");
                                });

                            b1.Navigation("MaxAmount")
                                .IsRequired();

                            b1.Navigation("MaxPercent")
                                .IsRequired();

                            b1.Navigation("MinAmount")
                                .IsRequired();

                            b1.Navigation("MinPercent")
                                .IsRequired();
                        });

                    b.OwnsOne("Khadra.Domain.Common.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");
                        });

                    b.Navigation("DeliveryLocation");

                    b.Navigation("Penalty");

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();

                    b.Navigation("Terms")
                        .IsRequired();
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.BookingStatusChange", b =>
                {
                    b.HasOne("Khadra.Domain.Bookings.Booking", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_changes_bookings_booking_id");
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.HandoverRecord", b =>
                {
                    b.HasOne("Khadra.Domain.Bookings.Booking", null)
                        .WithMany("Handovers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_handovers_bookings_booking_id");

                    b.OwnsOne("Khadra.Domain.Common.Money", "CashCollected", b1 =>
                        {
                            b1.Property<Guid>("HandoverRecordId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cash_collected_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("cash_collected_currency");

                            b1.HasKey("HandoverRecordId");

                            b1.ToTable("booking_handovers");

                            b1.WithOwner()
                                .HasForeignKey("HandoverRecordId")
                                .HasConstraintName("fk_booking_handovers_booking_handovers_id");
                        });

                    b.Navigation("CashCollected");
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.Dealer", b =>
                {
                    b.OwnsOne("Khadra.Domain.Common.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("DealerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("DealerId");

                            b1.ToTable("dealers");

                            b1.WithOwner()
                                .HasForeignKey("DealerId")
                                .HasConstraintName("fk_dealers_dealers_id");
                        });

                    b.OwnsOne("Khadra.Domain.Dealers.DeliverySettings", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("DealerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("delivery_enabled");

                            b1.Property<decimal>("RadiusKm")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("delivery_radius_km");

                            b1.HasKey("DealerId");

                            b1.ToTable("dealers");

                            b1.WithOwner()
                                .HasForeignKey("DealerId")
                                .HasConstraintName("fk_dealers_dealers_id");
                        });

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.DealerDocument", b =>
                {
                    b.HasOne("Khadra.Domain.Dealers.Dealer", null)
                        .WithMany("Documents")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dealer_documents_dealers_dealer_id");
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.Employee", b =>
                {
                    b.HasOne("Khadra.Domain.Dealers.Dealer", null)
                        .WithMany("Employees")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dealer_employees_dealers_dealer_id");
                });

            modelBuilder.Entity("Khadra.Domain.Disputes.DisputeStatement", b =>
                {
                    b.HasOne("Khadra.Domain.Disputes.DisputeTicket", null)
                        .WithMany("Statements")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_statements_dispute_tickets_ticket_id");
                });

            modelBuilder.Entity("Khadra.Domain.Disputes.DisputeTicket", b =>
                {
                    b.OwnsOne("Khadra.Domain.Disputes.DisputeResolution", "Resolution", b1 =>
                        {
                            b1.Property<Guid>("DisputeTicketId");

                            b1.Property<Guid>("ResolvedByAdminId");

                            b1.HasKey("DisputeTicketId");

                            b1.ToTable("dispute_tickets");

                            b1
                                .ToJson("resolution")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DisputeTicketId")
                                .HasConstraintName("fk_dispute_tickets_dispute_tickets_id");

                            b1.OwnsOne("Khadra.Domain.Disputes.DepositDisposition", "Deposit", b2 =>
                                {
                                    b2.Property<Guid>("DisputeResolutionDisputeTicketId");

                                    b2.HasKey("DisputeResolutionDisputeTicketId")
                                        .HasName("pk_dispute_tickets");

                                    b2.ToTable("dispute_tickets");

                                    b2.WithOwner()
                                        .HasForeignKey("DisputeResolutionDisputeTicketId")
                                        .HasConstraintName("fk_dispute_tickets_dispute_tickets_dispute_resolution_dispute_tic");

                                    b2.OwnsOne("Khadra.Domain.Common.Money", "RefundToCustomer", b3 =>
                                        {
                                            b3.Property<Guid>("DepositDispositionDisputeResolutionDisputeTicketId");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 3);

                                            b3.Property<string>("CurrencyCode")
                                                .IsRequired()
                                                .HasMaxLength(3);

                                            b3.HasKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasName("pk_dispute_tickets");

                                            b3.ToTable("dispute_tickets");

                                            b3.WithOwner()
                                                .HasForeignKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasConstraintName("fk_dispute_tickets_dispute_tickets_deposit_disposition_dispute_re");
                                        });

                                    b2.OwnsOne("Khadra.Domain.Common.Money", "RetainedByPlatform", b3 =>
                                        {
                                            b3.Property<Guid>("DepositDispositionDisputeResolutionDisputeTicketId");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 3);

                                            b3.Property<string>("CurrencyCode")
                                                .IsRequired()
                                                .HasMaxLength(3);

                                            b3.HasKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasName("pk_dispute_tickets");

                                            b3.ToTable("dispute_tickets");

                                            b3.WithOwner()
                                                .HasForeignKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasConstraintName("fk_dispute_tickets_dispute_tickets_deposit_disposition_dispute_re");
                                        });

                                    b2.OwnsOne("Khadra.Domain.Common.Money", "TransferredToDealer", b3 =>
                                        {
                                            b3.Property<Guid>("DepositDispositionDisputeResolutionDisputeTicketId");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 3);

                                            b3.Property<string>("CurrencyCode")
                                                .IsRequired()
                                                .HasMaxLength(3);

                                            b3.HasKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasName("pk_dispute_tickets");

                                            b3.ToTable("dispute_tickets");

                                            b3.WithOwner()
                                                .HasForeignKey("DepositDispositionDisputeResolutionDisputeTicketId")
                                                .HasConstraintName("fk_dispute_tickets_dispute_tickets_deposit_disposition_dispute_re");
                                        });

                                    b2.Navigation("RefundToCustomer")
                                        .IsRequired();

                                    b2.Navigation("RetainedByPlatform")
                                        .IsRequired();

                                    b2.Navigation("TransferredToDealer")
                                        .IsRequired();
                                });

                            b1.OwnsOne("Khadra.Domain.Common.Money", "DealerCharge", b2 =>
                                {
                                    b2.Property<Guid>("DisputeResolutionDisputeTicketId");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3);

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3);

                                    b2.HasKey("DisputeResolutionDisputeTicketId")
                                        .HasName("pk_dispute_tickets");

                                    b2.ToTable("dispute_tickets");

                                    b2.WithOwner()
                                        .HasForeignKey("DisputeResolutionDisputeTicketId")
                                        .HasConstraintName("fk_dispute_tickets_dispute_tickets_dispute_resolution_dispute_tic");
                                });

                            b1.Navigation("DealerCharge");

                            b1.Navigation("Deposit")
                                .IsRequired();
                        });

                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("Khadra.Domain.IdentityAccess.RefreshToken", b =>
                {
                    b.HasOne("Khadra.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Khadra.Domain.IdentityAccess.VerificationToken", b =>
                {
                    b.HasOne("Khadra.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verification_tokens_users_user_id");
                });

            modelBuilder.Entity("Khadra.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Handovers");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Khadra.Domain.Dealers.Dealer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Khadra.Domain.Disputes.DisputeTicket", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
