using System.Text.RegularExpressions;

namespace Khadra.Infrastructure.Documents;

/// <summary>
/// What a storage key is allowed to look like, for every provider that stores one.
/// </summary>
/// <remarks>
/// Extracted from <see cref="LocalDocumentStorage"/> when a second provider arrived, because the
/// alternative was each provider inventing its own idea of a safe key — and they would have differed
/// in exactly the way that matters. On a filesystem a bad key escapes the root; against an object
/// store the same key becomes a URL PATH, where <c>?</c> starts a query, <c>#</c> truncates, a leading
/// <c>/</c> re-roots the request and <c>..</c> may be collapsed by an intermediary before the store
/// ever sees it. One whitelist answers all of that, and answers it the same way twice.
///
/// A whitelist, not a blacklist. Keys are generated by this platform — scope, an id, a guid and one
/// of five extensions — so anything outside that shape is either a bug or an attack, and there is no
/// third case worth accommodating. Belt and braces even so: a key eventually comes back from the
/// database and from a signed token, and validating is far cheaper than trusting that every future
/// write path stayed disciplined.
/// </remarks>
internal static partial class DocumentKeys
{
    /// <summary>Throws unless the key is one this platform could have generated.</summary>
    public static string Validate(string? storageKey) =>
        !string.IsNullOrWhiteSpace(storageKey) && KeyPattern().IsMatch(storageKey)
            ? storageKey
            : throw new InvalidOperationException("The document key is not valid.");

    /// <summary>Throws unless the scope is a folder this platform could have chosen.</summary>
    public static string ValidateScope(string? scope) =>
        !string.IsNullOrWhiteSpace(scope) && ScopePattern().IsMatch(scope)
            ? scope
            : throw new InvalidOperationException("The document scope is not valid.");

    /// <summary>
    /// The extension to store under: the uploaded name's, when it is one of the five allowed, and
    /// otherwise one derived from the declared content type. Never an extension nobody vouched for.
    /// </summary>
    public static string Extension(string? fileName, string? contentType)
    {
        var extension = Path.GetExtension(fileName ?? string.Empty).ToLowerInvariant();
        if (extension is ".jpg" or ".jpeg" or ".png" or ".webp" or ".pdf")
            return extension;

        return contentType?.ToLowerInvariant() switch
        {
            "image/png" => ".png",
            "image/webp" => ".webp",
            "application/pdf" => ".pdf",
            _ => ".jpg"
        };
    }

    [GeneratedRegex(@"^[a-z-]+/[0-9a-f-]+$")]
    private static partial Regex ScopePattern();

    // Scope, id, file. The scope may carry a hyphen (dealer-branding) and the file stem a word before
    // its guid (logo-…, cover-…); nothing else, and never a path separator or a dot in the stem.
    [GeneratedRegex(@"^[a-z-]+/[0-9a-f-]+/[0-9a-z-]+\.(jpg|jpeg|png|webp|pdf)$")]
    private static partial Regex KeyPattern();
}
